name: RSpec Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        ports: ["5432:5432"]
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD:
          POSTGRES_DB: stray_paw_bridge_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.4'
          bundler-cache: true

      - name: Setup test database config
        run: cp config/database.yml.ci config/database.yml

      - name: Setup database
        run: bin/rails db:prepare

      - name: Print SimpleCov Coverage Summary
        run: |
          bundle exec rspec
          cat coverage/.last_run.json | jq '.result.covered_percent'
          
      - name: Run tests
        run: bundle exec rspec

