name: RSpec Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        ports: ["5432:5432"]
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: stray_paw_bridge_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.4'
          bundler-cache: true

      - name: Setup test database config
        run: cp config/database.yml.ci config/database.yml

      - name: Setup database
        run: RAILS_ENV=test bin/rails db:prepare

      - name: Precompile assets
        run: bundle exec rake assets:precompile

      - name: Run tests and print coverage
        run: |
          bundle exec rspec
          if [ -f coverage/.last_run.json ]; then
            echo "Coverage Summary:"
            cat coverage/.last_run.json | jq '.result.covered_percent'
          fi

      - name: Clean up assets
        run: rm -rf public/assets
